DATA:
  DATA_ROOT: '/scratch/yc6317/EgoPAT3D/dataset.hdf5'
MODEL:
  MODEL_NAME: 'baseline_rgb_convnext_t'
  ARCH:
    POINTCLOUD: False
    RGB: True
    RGB_BACKBONE: 'ConvNext_Tiny'
    POS_ENCODING: None
TRAINING:
  NUM_EPOCHS: 40
  OPTIMIZER: 'Adam'
  LEARNING_RATE: 0.0005
  DECAY_RATE: 1e-05
  LOSS: 'RGB_Ori'

  
